Feature/cannes 29
ANYF-Studios/cannesAPI pull request #14
Opened 2021-02-03 02:21 UTC by Nat67

Get orders for CMS

2021-02-03 04:07 UTC, morenoloza98 requested changes

2021-02-03 04:07 UTC, morenoloza98 commented on routes/controllers/orders.js
> +	Orders.find(function (err, orders) {
orders.find({}. (err, orders) => {...}

2021-02-04 18:14 UTC, A-lm14 requested changes
Cambiar los comentarios para mantener constancia en nuestras convenciones de código.

2021-02-04 18:14 UTC, A-lm14 commented on routes/handler.js
> +router.get('/orders',  passport.authenticate('jwt', {session: false}), orders.getOrders);
Utilizar snake_case en lugar de camelCase -> get_orders

2021-02-04 18:14 UTC, A-lm14 commented on routes/controllers/orders.js
> +exports.getOrders = (req, res, next) => {
Utilizar snake_case en lugar de camelCase -> get_orders = ...

2021-02-05 02:32 UTC, A-lm14 requested changes

2021-02-05 02:32 UTC, A-lm14 commented on routes/handler.js
> +let orders = require ('./controllers/ordersController');
El archivo igua tiene que estar en snake_case

2021-02-05 04:22 UTC, A-lm14 approved these changes

2021-02-05 04:43 UTC, morenoloza98 approved these changes

2021-02-05 04:48 UTC, merged